### ISSUE TITLE
ERROR: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by ychaker** [browsermedia/bcms_event#1]
After installing the bcms_event module, looking at the event page created shows the following error:
ERROR: undefined method `name' for nil:NilClass
which is coming from the Event Details portlet.
I surrounded the code of the portlet by an if statement to get rid of the error

**Comment by peakpg** [comment]
Scheduling for 1.1.0 release

**Comment by peakpg** [comment]
Fixed. Adding a more helpful error message similar to how bcms_news does it.
